# Generated by Django 6.0.2 on 2026-02-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_dailyverse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyverse',
            name='image',
            field=models.ImageField(upload_to='verses/'),
        ),
    ]
