# Generated by Django 6.0.2 on 2026-02-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_dailyverse_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='meetings/')),
                ('description', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
