# Generated by Django 6.0.2 on 2026-02-21 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_galleryfolder_galleryimage_uploaded_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrayerRequest',
        ),
    ]
