# Generated by Django 6.0.2 on 2026-02-21 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_delete_prayerrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
